### PR TITLE
release v1.2.0

### PR DESCRIPTION
**Pull request by Meherdeep**
- Added screen sharing for Android/iOS
- Added layout for one to one video calling
- Fixes issue [#122](https://github.com/AgoraIO-Community/VideoUIKit-Flutter/issues/122)

### CODE REVIEW

**Comment by tadaspetra** [comment]
Several Issues I ran into:

* If clicking screenshare, then cancel before starting it, button shows active screenshare.
* While screen sharing, local user turns off camera feed, the screenshare will stop
* iOS screenshare not coming through on other device
* audio coming through even though mic is disabled

**Comment by Meherdeep** [comment]
@maxxfrazer @tadaspetra I made some changes to the PR that solves all the issues reported in the above comment. Please take a look at it.

**Comment by maxxfrazer** [comment]
nice one! will take a look and run from my end.

**Review by tadaspetra — APPROVED** [review]
Looks good!

**Review by tadaspetra — APPROVED** [review]

**Review by maxxfrazer — APPROVED** [review]
LGTM

**Pull request merged**
